### ISSUE TITLE
请问在我自己的数据集上为什么accuracy、f1score没有随着训练迭代过程提高呢。

### ISSUE THREAD

**Issue by chenz1hao** [12wang3/mllp#1]
![image](https://user-images.githubusercontent.com/16265544/140925149-91668ec4-282c-4f6f-aae4-1a202ef943b2.png)
生成的pdf看到训练过程中loss减少的很少，accuracy 和 f1 score更是相当震荡的，这个考虑是什么方面的问题呢。谢谢

**Comment by 12wang3** [comment]
你好，由于不了解你的数据集，我也不太确定为什么training set上的Accuracy没有提升。
不过有几个地方你可以尝试一下，首先可以看出loss还有很大的下降空间，因此你可以试一下，把epoch（-e选项）调高，例如800或1200。另外你还可以尝试调节一下learning rate（-lr选项）。此外，可以看出MLLP的结果远好于CRS，这可能是由于random binarization rate（-p选项）设置的不合理。
不过我更推荐你使用我们最新的工作[https://github.com/12wang3/rrl](https://github.com/12wang3/rrl)，该工作同样可以学习离散规则，并能够直接优化离散模型，还有更好的可扩展性。

**Comment by chenz1hao** [comment]
好的感谢建议
