### ISSUE TITLE
倒数第二层(2L-1)中某个node（合取规则）如果与最后一层(2L)的class node有多条连边(weight=1)时的处理

### ISSUE THREAD

**Issue by chenz1hao** [12wang3/mllp#2]
（1）你好，文中描述的这个情况：
![image](https://user-images.githubusercontent.com/16265544/143245985-7487e9b0-f904-4087-b4f9-6bb20a7f98b6.png)
我理解是否就是这样，就是在权重离散化后正向传播过程中倒数第二层的合取规则与最后一层的两个节点（如果二分类）都有连边，即权重都为1，那就选择第一个class node作为该合取规则的分类标签，但这样的话是否有些不太科学或者是降低了性能（这样可能就等于是随机分类了？），在RRL中，最后一层的weight不会被离散化，保持在[-1,1]之间，但是这样得到的解释集就没那么直观了，相当于只能得到每条规则重要程度。
![image](https://user-images.githubusercontent.com/16265544/143246687-4e003970-bfe4-4047-8a15-172441719686.png)
（2）另外一个小问题就是对于网络结构的初始化，如果参数 -s 64_32_16，那么得到的网络的中间层是否应该是 [64, 64, 32, 32, 16]这样的结构（最后一层以合取层16个节点结束），但是实际建立的网络好像并不是这样的
![image](https://user-images.githubusercontent.com/16265544/143248336-ef713dc7-ffa2-4430-9283-2a6bb2053025.png)
![image](https://user-images.githubusercontent.com/16265544/143248297-cdfb4290-af65-41f5-9c72-6125373b1dfb.png)
不知道是我理解还有问题吗，谢谢啦。

**Comment by 12wang3** [comment]
你好，以下为具体解答：
（1）文中描述的这个情况是指在测试阶段，对于一个实例，模型最后一层有多个节点被激活，也就是说模型认为有多个类别都可能符合。但由于激活值是离散化的，不像概率值有大小的区别，所以我们无法判断哪一个类别更符合。文中我是直接取第一个激活了的类别，实际操作时也可以取训练集中实例数更多的那个激活了的类别（即该类别可能性更大）。RRL最后一层是一个线性层，这样就能计算概率值了，并且能够更好地处理数据的线性部分。当然，线性层的连续值确实不如全部离散值可解释性好，这属于做了取舍。
（2）“-s 64_32_16”是指第一层conjunction layer的节点数为64，第二层disjunction layer的节点数为32，第三层conjunction layer的节点数为16。而最后一层（也就是第四层）的disjunction layer的节点数是类别个数，不需要指定。另外，一个level中的conjunction layer和disjunction layer的节点数不需要相同，所以这里是分别指定。
